// <auto-generated />
using System;
using System.Collections.Generic;
using IntegrationAPI.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegrationAPI.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    [Migration("20260305072858_ChatMembersAndVehiclesAndTransportCargoTypesTablesAdded")]
    partial class ChatMembersAndVehiclesAndTransportCargoTypesTablesAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BaseLibrary.Model.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CargoTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DangerLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShippingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShippingOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Dimensions", "BaseLibrary.Model.Cargo.Dimensions#Dimensions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Height")
                                .HasColumnType("REAL");

                            b1.Property<double>("Length")
                                .HasColumnType("REAL");

                            b1.Property<double>("Width")
                                .HasColumnType("REAL");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CargoTypeId");

                    b.HasIndex("ShippingId");

                    b.HasIndex("ShippingOrderId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("BaseLibrary.Model.CargoType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CargoTypes");
                });

            modelBuilder.Entity("BaseLibrary.Model.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivateChat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("BaseLibrary.Model.ChatMember", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ChatId");

                    b.HasIndex("MemberId");

                    b.ToTable("ChatMembers");
                });

            modelBuilder.Entity("BaseLibrary.Model.Driver", b =>
                {
                    b.Property<int>("Rights")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("BaseLibrary.Model.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BaseLibrary.Model.Shipping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DesignatedDriverId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedDeliveryCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EstimatedDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedDeliveryPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ShippedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DesignatedDriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("BaseLibrary.Model.ShippingOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShippingOrders");
                });

            modelBuilder.Entity("BaseLibrary.Model.TransportCargoTypes", b =>
                {
                    b.Property<int>("CargoTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CargoTypeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("TransportCargoTypes");
                });

            modelBuilder.Entity("BaseLibrary.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PassHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BaseLibrary.Model.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("FuelType")
                        .HasColumnType("INTEGER");

                    b.Property<float>("LiftingCapacity")
                        .HasColumnType("REAL");

                    b.Property<float>("MaxCargoVolume")
                        .HasColumnType("REAL");

                    b.Property<float>("MaxFuelVolume")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<byte>("NumberOfAxes")
                        .HasColumnType("INTEGER");

                    b.Property<float>("VehicleWeight")
                        .HasColumnType("REAL");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "VehicleSize", "BaseLibrary.Model.Vehicle.VehicleSize#Dimensions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Height")
                                .HasColumnType("REAL");

                            b1.Property<double>("Length")
                                .HasColumnType("REAL");

                            b1.Property<double>("Width")
                                .HasColumnType("REAL");
                        });

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("BaseLibrary.Model.Cargo", b =>
                {
                    b.HasOne("BaseLibrary.Model.CargoType", "CargoType")
                        .WithMany()
                        .HasForeignKey("CargoTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseLibrary.Model.Shipping", "Shipping")
                        .WithMany("Cargos")
                        .HasForeignKey("ShippingId");

                    b.HasOne("BaseLibrary.Model.ShippingOrder", "ShippingOrder")
                        .WithMany("Cargos")
                        .HasForeignKey("ShippingOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoType");

                    b.Navigation("Shipping");

                    b.Navigation("ShippingOrder");
                });

            modelBuilder.Entity("BaseLibrary.Model.ChatMember", b =>
                {
                    b.HasOne("BaseLibrary.Model.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseLibrary.Model.User", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BaseLibrary.Model.Driver", b =>
                {
                    b.HasOne("BaseLibrary.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseLibrary.Model.Message", b =>
                {
                    b.HasOne("BaseLibrary.Model.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseLibrary.Model.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BaseLibrary.Model.Shipping", b =>
                {
                    b.HasOne("BaseLibrary.Model.User", "DesignatedDriver")
                        .WithMany()
                        .HasForeignKey("DesignatedDriverId");

                    b.HasOne("BaseLibrary.Model.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignatedDriver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("BaseLibrary.Model.TransportCargoTypes", b =>
                {
                    b.HasOne("BaseLibrary.Model.CargoType", "CargoType")
                        .WithMany()
                        .HasForeignKey("CargoTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseLibrary.Model.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("BaseLibrary.Model.Shipping", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("BaseLibrary.Model.ShippingOrder", b =>
                {
                    b.Navigation("Cargos");
                });
#pragma warning restore 612, 618
        }
    }
}
